-- Tạo bảng hoan_tien nếu chưa tồn tại
CREATE TABLE IF NOT EXISTS hoan_tien (
    HT_MA INT AUTO_INCREMENT PRIMARY KEY,
    HD_STT INT NOT NULL,
    HT_SOTIEN DECIMAL(15,2) NOT NULL,
    HT_MAGIAODICH VARCHAR(50) NOT NULL,
    HT_LYDO TEXT NOT NULL,
    HT_TRANGTHAI ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED') NOT NULL DEFAULT 'PENDING',
    HT_NGAYTAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    HT_NGAYCAPNHAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    HT_GHICHU TEXT,
    FOREIGN KEY (HD_STT) REFERENCES hoa_don(HD_STT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tạo index cho các trường thường xuyên tìm kiếm
CREATE INDEX idx_hoan_tien_trangthai ON hoan_tien(HT_TRANGTHAI);
CREATE INDEX idx_hoan_tien_magiaodich ON hoan_tien(HT_MAGIAODICH); 