CREATE TABLE IF NOT EXISTS benh_cay_trong (
    BENH_MA INT AUTO_INCREMENT PRIMARY KEY,
    BENH_TEN VARCHAR(255) NOT NULL,
    BENH_MOTA TEXT,
    BENH_TRIEUCHUNG TEXT,
    BENH_CACHDIEUTRI TEXT,
    BENH_HINHANH VARCHAR(255),
    BENH_TRANGTHAI TINYINT(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 