-- Tạo bảng lịch sử tồn kho
CREATE TABLE IF NOT EXISTS lich_su_ton_kho (
    LSTK_MA INT AUTO_INCREMENT PRIMARY KEY,
    SP_MA VARCHAR(50) NOT NULL,
    LSTK_LOAI VARCHAR(20) NOT NULL, -- 'increase' hoặc 'decrease'
    LSTK_SOLUONG DECIMAL(10,2) NOT NULL,
    LSTK_LYDO TEXT,
    LSTK_GIANHAP DECIMAL(10,2) DEFAULT 0,
    LSTK_TONGTIEN DECIMAL(10,2) DEFAULT 0,
    NV_MA INT NOT NULL,
    LSTK_THOIGIAN TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SP_MA) REFERENCES san_pham(SP_MA),
    FOREIGN KEY (NV_MA) REFERENCES nhan_vien(NV_MA)
); 