-- Cập nhật cấu trúc bảng lich_su_ton_kho
ALTER TABLE lich_su_ton_kho
MODIFY COLUMN LSTK_MA INT(11) AUTO_INCREMENT PRIMARY KEY,
MODIFY COLUMN SP_MA INT(11) NOT NULL,
MODIFY COLUMN LSTK_LOAI VARCHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'Loại điều chỉnh: NHAP/XUAT/DIEU_CHINH',
MODIFY COLUMN LSTK_SOLUONG INT(11) NOT NULL COMMENT 'Số lượng thay đổi',
MODIFY COLUMN LSTK_SOLUONG_CU INT(11) NOT NULL COMMENT 'Số lượng trước khi thay đổi',
MODIFY COLUMN LSTK_SOLUONG_MOI INT(11) NOT NULL COMMENT 'Số lượng sau khi thay đổi',
MODIFY COLUMN LSTK_GHICHU TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'Lý do điều chỉnh',
MODIFY COLUMN NV_MA INT(11) NULL DEFAULT NULL COMMENT 'Mã nhân viên thực hiện',
MODIFY COLUMN LSTK_THOIGIAN TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS LSTK_THAMCHIEU VARCHAR(50) NULL DEFAULT NULL COMMENT 'Tham chiếu đến phiếu nhập/xuất nếu có'; 